development:
  mysql41: 9110
  morphology: stem_en
  enable_star: true
  html_strip: 1
  min_infix_len: 2
  bin_path: "/usr/local/bin"
  host: 127.0.0.1
test:
  mysql41: 9111
  morphology: stem_en
  enable_star: true
  html_strip: 1
  min_infix_len: 2
production:
  morphology: stem_en
  enable_star: true
  html_strip: 1
  min_infix_len: 2
