development:
  version: 3.0.3
  mysql41: 9110
  morphology: stem_en
  html_strip: 1
  min_infix_len: 2
  bin_path: "/usr/local/bin"
  searchd_binary_name: searchd
  indexer_binary_name: indexer
  host: 127.0.0.1
test:
  version: 3.0.3
  mysql41: 9110
  morphology: stem_en
  html_strip: 1
  min_infix_len: 2
production:
  version: 3.0.3
  mysql41: 9110
  morphology: stem_en
  html_strip: 1
  min_infix_len: 2
